/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Disputes;

/**
 *
 * @author Wise
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class DisputeMain extends javax.swing.JFrame {
    
    /**
     * Creates new form Dispute
     */
    public DisputeMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmDialog = new javax.swing.JDialog();
        jConfirmButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();
        jLabelConfirm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonDispute = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCommentArea = new javax.swing.JTextArea();

        confirmDialog.setAlwaysOnTop(true);
        confirmDialog.setMinimumSize(new java.awt.Dimension(300, 100));
        confirmDialog.setModal(true);
        confirmDialog.setName("confirmDialog"); // NOI18N

        jConfirmButton.setText("Yes");
        jConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmButtonActionPerformed(evt);
            }
        });

        jCancelButton.setText("No");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        jLabelConfirm.setText("Are you sure you want to send this dispute?");

        javax.swing.GroupLayout confirmDialogLayout = new javax.swing.GroupLayout(confirmDialog.getContentPane());
        confirmDialog.getContentPane().setLayout(confirmDialogLayout);
        confirmDialogLayout.setHorizontalGroup(
            confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addGroup(confirmDialogLayout.createSequentialGroup()
                        .addComponent(jConfirmButton)
                        .addGap(18, 18, 18)
                        .addComponent(jCancelButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        confirmDialogLayout.setVerticalGroup(
            confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jConfirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Enter comment: (max. 250 characters, including spaces)");

        jButtonDispute.setText("Submit Dispute");
        jButtonDispute.setEnabled(false);
        jButtonDispute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDisputeActionPerformed(evt);
            }
        });

        jCommentArea.setColumns(20);
        jCommentArea.setLineWrap(true);
        jCommentArea.setRows(5);
        jCommentArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCommentAreaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jCommentArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButtonDispute))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDispute)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDisputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDisputeActionPerformed
        // TODO add your handling code here:
        //when button pressed, assign the text to variable comment
        String comment = jCommentArea.getText();
        confirmDialog.setVisible(true);
    }//GEN-LAST:event_jButtonDisputeActionPerformed

    private void jCommentAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCommentAreaKeyTyped
        // TODO add your handling code here:
        if (jCommentArea.getText().length() != 0) {
            //if the text length is not 0, show dispute button
            jButtonDispute.setEnabled(true);
        }
        else {
            //else button can not be clicked
            jButtonDispute.setEnabled(false);
        }
        if (jCommentArea.getText().length() >= 250){
            evt.consume();
        }
    }//GEN-LAST:event_jCommentAreaKeyTyped

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        // TODO add your handling code here:
        //close the dialog
        confirmDialog.dispose();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void jConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmButtonActionPerformed
        // TODO add your handling code here:
        //database credentials
        String host = "jdbc:derby://localhost:1527/ECS2";
        String username = "admin1";
        String password = "admin1";
        
        try {
            //try to connect to databse with database credentials
            Connection con = DriverManager.getConnection(host, username, password);
            
            //using dummy data for a piece of coursework to update dispute fields
            PreparedStatement statement = con.prepareStatement("UPDATE SUBMISSION SET despute = ?, Comment = ? WHERE Student_ID = ?");
            statement.setString(1, "True");
            statement.setString(2, jCommentArea.getText());
            statement.setString(3, "1"); 
            statement.executeUpdate();
            System.out.println("Database has been updated!");
            confirmDialog.dispose();
            jCommentArea.setEnabled(false);
            jButtonDispute.setEnabled(false);
        }
        catch(SQLException err) {
            //if it fails, throw an error message
            System.out.println(err.getMessage());
        }
        //code needed to notify staff about dispute
        
    }//GEN-LAST:event_jConfirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisputeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisputeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisputeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisputeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DisputeMain().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog confirmDialog;
    private javax.swing.JButton jButtonDispute;
    private javax.swing.JButton jCancelButton;
    private javax.swing.JTextArea jCommentArea;
    private javax.swing.JButton jConfirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConfirm;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}

