/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jump;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kenneth
 */
public class Win extends javax.swing.JFrame {
    
    /**
     * Creates new form Win
     */
    public Win() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Click = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        browseb = new javax.swing.JButton();
        FilePathLable = new javax.swing.JLabel();
        previewB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Download Page");

        Click.setText("Click");
        Click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickActionPerformed(evt);
            }
        });

        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        browseb.setText("Browse");
        browseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsebActionPerformed(evt);
            }
        });

        FilePathLable.setText("File Path:");

        previewB.setText("Preview");
        previewB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewBActionPerformed(evt);
            }
        });

        ShowBox.setColumns(20);
        ShowBox.setRows(5);
        jScrollPane1.setViewportView(ShowBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FilePathLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(path, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseb))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Click, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(previewB)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previewB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseb)
                    .addComponent(FilePathLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Click)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void ClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickActionPerformed
        // TODO add your handling code here:
        try{
            new pop().setVisible(true); 
        }catch(Exception e){
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_ClickActionPerformed

    private void browsebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebActionPerformed
        // TODO add your handling code here:
        
        // parent component of the dialog
        JFrame parentFrame = new JFrame();
        
        JFileChooser fileChooser = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("PDF File","pdf");
        fileChooser.setDialogTitle("Save as");
        fileChooser.setFileFilter(filter);
        
        int userSelection = fileChooser.showSaveDialog(parentFrame);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            String filename = fileToSave.getAbsolutePath();
            
            for (int i = filename.length()-1 ; i!= 0; --i){
                if (filename.substring(i).equals(".pdf")){
                    ;
                }else{
                    path.setText(filename+ ".pdf");                    
                };
            };

        } else if (userSelection == JFileChooser.CANCEL_OPTION) {
            parentFrame.setVisible(false); 
        }
        
        
        
        
        
    }//GEN-LAST:event_browsebActionPerformed

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed
    
    // Here is  the code of preview the student information
    private void previewBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewBActionPerformed
        // TODO add your handling code here:
        try{
            String location = "jdbc:derby://localhost:1527/Student";
            String username = "Admin1";
            String password = "password";
            
            Connection cnt = DriverManager.getConnection(location, username, password);
            Statement stmt = cnt.createStatement();
            
            //Query to select the student information uding the student id.
            String skey = "SELECT * FROM STUDENT WHERE STUDENT_ID = '1'";
            ResultSet srs = stmt.executeQuery(skey);
            
            //go thought the database
            srs.next();
            
            //Setting Value 
            String fn=srs.getString(2);
            String ln=srs.getString(3);
            String sid=srs.getString(1);
            String courseid= srs.getString(4); //the course id will be used as a key acesss 
            
            //Let student preview their information
            ShowBox.setText("Below is your information: \n"
                    +"\nFirst Name: "+ fn
                    +"\nLast Name: "+ ln
                    +"\nSID:"+ sid
                    +"\n");
            
                        
            
            ///Using the course id to  get the information of the moudle
            String ckey = "SELECT * FROM COURSE WHERE COURSE_ID = '"+courseid +"'";
            ResultSet crs = stmt.executeQuery(ckey);
            
            
            crs.next();
            //add in line to the ShowBox
            ShowBox.append("Course ID: "+ crs.getString(1) +
                    "\nCourse Name: "+ crs.getString(2) +
                    "\n");
            
            
            
            
            //geting the course id form the student table
            //String courseid= crs.getString(1);            
            
            ///Using the course id to  get the information of the moudle
            String mkey = "SELECT * FROM MODULE WHERE COURSE_ID = '"+ courseid +"'";
            ResultSet mrs = stmt.executeQuery(mkey);
            
            
            mrs.next();
            //add in line to the ShowBox
            ShowBox.append("Module ID: "+ mrs.getString(1) +
                    "\nMoudle Name: "+ mrs.getString(2) +
                    "\n");
            
            /*
            String mkey = "SELECT * FROM MODULE WHERE COURSE_ID = '"+ courseid +"'";
            ResultSet mrs = stmt.executeQuery(mkey);
            
            
            mrs.next();
            //add in line to the ShowBox
            ShowBox.append("Module ID: "+ mrs.getString(1) +
                    "\nMoudle Name: "+ mrs.getString(2) +
                    "\n");
                    */





            
            //Disable the edit function
            ShowBox.setEditable(false);
        
            }catch(SQLException ex) {
                JOptionPane.showMessageDialog(null,ex.toString());
            }   
        

    }//GEN-LAST:event_previewBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Win().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Click;
    private javax.swing.JLabel FilePathLable;
    private javax.swing.JTextArea ShowBox;
    private javax.swing.JButton browseb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField path;
    private javax.swing.JButton previewB;
    // End of variables declaration//GEN-END:variables
}