package Report;

//@author jeffordl
public class GenerateReport extends javax.swing.JFrame {

    //Creates new form GenerateReport
    public GenerateReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        GeneralReportPanel = new javax.swing.JPanel();
        GRAllCW = new javax.swing.JRadioButton();
        GRSubmittedCW = new javax.swing.JRadioButton();
        GROutstandingCW = new javax.swing.JRadioButton();
        GRGradedCW = new javax.swing.JRadioButton();
        scrollPane1 = new java.awt.ScrollPane();
        textArea1 = new java.awt.TextArea();
        jPanel3 = new javax.swing.JPanel();
        WindowLabel = new javax.swing.JLabel();
        DownloadRButton = new javax.swing.JButton();
        PrintRButton = new javax.swing.JButton();
        ClearRButton = new javax.swing.JButton();
        BackRButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        GRAllCW.setText("All CW");
        GRAllCW.setToolTipText("Bring up the list of all coursework listed on the system");
        GRAllCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRAllCWActionPerformed(evt);
            }
        });

        GRSubmittedCW.setText("Submitted CW");
        GRSubmittedCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRSubmittedCWActionPerformed(evt);
            }
        });

        GROutstandingCW.setText("Outstanding CW");

        GRGradedCW.setText("Graded CW");
        GRGradedCW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GRGradedCWActionPerformed(evt);
            }
        });

        scrollPane1.add(textArea1);

        javax.swing.GroupLayout GeneralReportPanelLayout = new javax.swing.GroupLayout(GeneralReportPanel);
        GeneralReportPanel.setLayout(GeneralReportPanelLayout);
        GeneralReportPanelLayout.setHorizontalGroup(
            GeneralReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeneralReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GeneralReportPanelLayout.createSequentialGroup()
                        .addComponent(GRAllCW)
                        .addGap(18, 18, 18)
                        .addComponent(GRSubmittedCW)
                        .addGap(18, 18, 18)
                        .addComponent(GROutstandingCW)
                        .addGap(18, 18, 18)
                        .addComponent(GRGradedCW)
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GeneralReportPanelLayout.setVerticalGroup(
            GeneralReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralReportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GeneralReportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GRAllCW)
                    .addComponent(GRSubmittedCW)
                    .addComponent(GROutstandingCW)
                    .addComponent(GRGradedCW))
                .addGap(2, 2, 2)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General Report", GeneralReportPanel);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        WindowLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        WindowLabel.setText("Submission Reports");

        DownloadRButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        DownloadRButton.setText("Download Report");

        PrintRButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PrintRButton.setText("Print Report");

        ClearRButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        ClearRButton.setText("Clear Report");

        BackRButton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        BackRButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackRButton)
                .addGap(18, 18, 18)
                .addComponent(ClearRButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(DownloadRButton)
                .addGap(18, 18, 18)
                .addComponent(PrintRButton)
                .addContainerGap())
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WindowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(WindowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DownloadRButton)
                    .addComponent(PrintRButton)
                    .addComponent(ClearRButton)
                    .addComponent(BackRButton))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>                        

    private void GRSubmittedCWActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void GRAllCWActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void GRGradedCWActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BackRButton;
    private javax.swing.JButton ClearRButton;
    private javax.swing.JButton DownloadRButton;
    private javax.swing.JRadioButton GRAllCW;
    private javax.swing.JRadioButton GRGradedCW;
    private javax.swing.JRadioButton GROutstandingCW;
    private javax.swing.JRadioButton GRSubmittedCW;
    private javax.swing.JPanel GeneralReportPanel;
    private javax.swing.JButton PrintRButton;
    private javax.swing.JLabel WindowLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.ScrollPane scrollPane1;
    private java.awt.TextArea textArea1;
    // End of variables declaration                   
}
